---
title: Audiobitts
timezone: America/Phoenix
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Audiobitts
markdown: kramdown
sass:
  sass_dir: _scss
